resources:
- manager.yaml
kind: Kustomization
images:
- name: ghcr.io/datum-labs/resource-metrics
  newName: ghcr.io/datum-labs/resource-metrics
  newTag: latest

configMapGenerator:
- files:
  - config.yaml
  name: resource-metrics-config
  options:
    disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
