name: publish-bundle

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-image:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.13.1
    with:
      image-name: resource-metrics
    secrets: inherit

  publish-kustomize-bundles:
    needs: build-image
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.13.1
    with:
      bundle-name: ghcr.io/datum-cloud/resource-metrics-kustomize
      bundle-path: config
      image-overlays: config/manager
      image-name: ghcr.io/datum-cloud/resource-metrics
    secrets: inherit
